#!/usr/bin/env python3
"""Build the PDHD-U1 formal 84-item reliability package only after codebook freeze.

This script is intentionally gated. In the current pre-validation state it must
refuse to generate a formal reliability package because `codebook_registry.csv`
contains only a calibration baseline. The gate opens only when exactly one
codebook row is explicitly registered as `frozen_for_independent_reliability`.

No annotation labels are generated by this script.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
from io import StringIO
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SAMPLES = ROOT / "data" / "samples"
REGISTRY = SAMPLES / "codebook_registry.csv"
RESERVE = SAMPLES / "reliability_reserve_0_1.csv"
MANIFEST = SAMPLES / "reliability_manifest_0_1.csv"
CODER_SHEET = SAMPLES / "reliability_coder_sheet_0_1.csv"
FROZEN_STATUS = "frozen_for_independent_reliability"
ORDER_NAMESPACE = "PDHD-REL-0.1"


def read_csv(path: Path) -> tuple[list[dict[str, str]], list[str]]:
    with path.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        return list(reader), list(reader.fieldnames or [])


def git_blob_sha(path: Path) -> str:
    payload = path.read_bytes()
    header = f"blob {len(payload)}\0".encode("ascii")
    return hashlib.sha1(header + payload).hexdigest()


def frozen_codebook(rows: list[dict[str, str]]) -> dict[str, str] | None:
    frozen = [r for r in rows if r.get("status", "").strip() == FROZEN_STATUS]
    if len(frozen) > 1:
        raise RuntimeError("more than one codebook is marked frozen for independent reliability")
    return frozen[0] if frozen else None


def verify_codebook(row: dict[str, str]) -> None:
    required = [
        ("annotation_manual_path", "annotation_manual_blob_sha"),
        ("pedagogical_acts_path", "pedagogical_acts_blob_sha"),
        ("pedagogical_dimensions_path", "pedagogical_dimensions_blob_sha"),
    ]
    version = row.get("codebook_version", "").strip()
    if not version:
        raise RuntimeError("frozen codebook row lacks codebook_version")
    for path_field, sha_field in required:
        rel = row.get(path_field, "").strip()
        expected = row.get(sha_field, "").strip()
        if not rel or not expected:
            raise RuntimeError(f"{version}: missing {path_field} or {sha_field}")
        path = ROOT / rel
        if not path.is_file():
            raise RuntimeError(f"{version}: registered codebook file does not exist: {rel}")
        actual = git_blob_sha(path)
        if actual != expected:
            raise RuntimeError(
                f"{version}: codebook blob mismatch for {rel}; registered={expected} actual={actual}"
            )


def frozen_union() -> dict[str, dict[str, str]]:
    result: dict[str, dict[str, str]] = {}
    for path in sorted(SAMPLES.glob("frozen_fragments*.csv")):
        rows, _ = read_csv(path)
        for row in rows:
            fid = row["fragment_id"]
            if fid in result:
                raise RuntimeError(f"duplicate frozen fragment across shards: {fid}")
            result[fid] = row
    if len(result) != 96:
        raise RuntimeError(f"expected 96 frozen fragments, found {len(result)}")
    return result


def annotation_fields() -> list[str]:
    _, fields = read_csv(SAMPLES / "annotation_pilot_template.csv")
    start = fields.index("coder_id")
    return fields[start:]


def order_score(codebook_version: str, fragment_id: str) -> str:
    payload = f"{ORDER_NAMESPACE}|{codebook_version}|{fragment_id}".encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def package_rows(codebook: dict[str, str]) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    verify_codebook(codebook)
    reserve_rows, _ = read_csv(RESERVE)
    if len(reserve_rows) != 84:
        raise RuntimeError(f"reliability reserve must contain 84 rows, found {len(reserve_rows)}")
    reserve_ids = {r["fragment_id"] for r in reserve_rows}
    if len(reserve_ids) != 84:
        raise RuntimeError("reliability reserve contains duplicate fragment IDs")

    frozen = frozen_union()
    if not reserve_ids <= set(frozen):
        raise RuntimeError("reliability reserve contains a non-frozen fragment")

    codebook_version = codebook["codebook_version"].strip()
    ordered = sorted(
        reserve_rows,
        key=lambda r: (order_score(codebook_version, r["fragment_id"]), r["fragment_id"]),
    )

    manifest_rows: list[dict[str, str]] = []
    coder_rows: list[dict[str, str]] = []
    for i, reserve in enumerate(ordered, 1):
        fid = reserve["fragment_id"]
        source = frozen[fid]
        if source.get("freeze_status") != "frozen":
            raise RuntimeError(f"formal reliability fragment is not frozen: {fid}")
        if reserve["document_id"] != source["document_id"]:
            raise RuntimeError(f"reserve/frozen document mismatch: {fid}")

        item_id = f"REL{i:03d}"
        manifest_rows.append(
            {
                "item_id": item_id,
                "reliability_order": str(i),
                "fragment_id": fid,
                "document_id": reserve["document_id"],
                "page": source["page"],
                "codebook_version": codebook_version,
                "reserve_version": reserve["reserve_version"],
                "order_namespace": ORDER_NAMESPACE,
                "selection_basis": "pre_registered_84_fragment_reserve",
                "status": "selected_for_formal_independent_reliability",
            }
        )

        coder = {
            "item_id": item_id,
            "fragment_id": fid,
            "document_id": reserve["document_id"],
            "page": source["page"],
            "source_url": source["locator_evidence_url"],
            "boundary_instruction": source["boundary_definition"],
            "codebook_version": codebook_version,
            "annotation_id": "",
        }
        for field in annotation_fields():
            coder[field] = ""
        coder_rows.append(coder)

    return manifest_rows, coder_rows


MANIFEST_FIELDS = [
    "item_id",
    "reliability_order",
    "fragment_id",
    "document_id",
    "page",
    "codebook_version",
    "reserve_version",
    "order_namespace",
    "selection_basis",
    "status",
]


def coder_fields() -> list[str]:
    return [
        "item_id",
        "fragment_id",
        "document_id",
        "page",
        "source_url",
        "boundary_instruction",
        "codebook_version",
        "annotation_id",
        *annotation_fields(),
    ]


def csv_text(rows: list[dict[str, str]], fields: list[str]) -> str:
    buf = StringIO(newline="")
    writer = csv.DictWriter(buf, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return buf.getvalue()


def expected_outputs(codebook: dict[str, str]) -> dict[Path, str]:
    manifest_rows, coder_rows = package_rows(codebook)
    return {
        MANIFEST: csv_text(manifest_rows, MANIFEST_FIELDS),
        CODER_SHEET: csv_text(coder_rows, coder_fields()),
    }


def current_gate() -> dict[str, str] | None:
    rows, _ = read_csv(REGISTRY)
    return frozen_codebook(rows)


def check_state() -> int:
    codebook = current_gate()
    if codebook is None:
        leaked = [str(p.relative_to(ROOT)) for p in (MANIFEST, CODER_SHEET) if p.exists()]
        if leaked:
            raise SystemExit(
                "formal reliability outputs exist before an independent-round codebook is frozen: "
                + ", ".join(leaked)
            )
        print(
            "PDHD formal reliability gate active: no codebook is marked "
            f"{FROZEN_STATUS}; no formal 84-item package exists"
        )
        return 0

    outputs = expected_outputs(codebook)
    mismatches = []
    for path, expected in outputs.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual != expected:
            mismatches.append(str(path.relative_to(ROOT)))
    if mismatches:
        raise SystemExit(
            "formal reliability gate is open but package is missing or non-reproducible: "
            + ", ".join(mismatches)
        )
    print(
        "PDHD formal reliability package check passed "
        f"(84 items; frozen codebook {codebook['codebook_version']})"
    )
    return 0


def self_test() -> int:
    assert frozen_codebook([]) is None
    assert frozen_codebook([{"status": "calibration_baseline"}]) is None
    row = {"status": FROZEN_STATUS, "codebook_version": "PDHD-CB-test"}
    assert frozen_codebook([row]) == row
    try:
        frozen_codebook([row, dict(row)])
    except RuntimeError:
        pass
    else:
        raise AssertionError("multiple frozen codebooks must be rejected")
    print("build_formal_reliability_package gate self-test passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check-state", action="store_true")
    mode.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        return self_test()
    if args.check_state:
        return check_state()

    codebook = current_gate()
    if codebook is None:
        raise SystemExit(
            "REFUSED: formal reliability package cannot be generated until exactly one "
            f"codebook is registered with status={FROZEN_STATUS!r}"
        )
    for path, text in expected_outputs(codebook).items():
        path.write_text(text, encoding="utf-8")
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
